services:
  mysql:
    image: mysql:8.0
    container_name: trophy_lab_backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: trophy_lab_backend
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local